import axios from "axios"
import { useState } from "react"
import Link from 'next/link'
import Image from 'next/image'
import {CheckCircle} from '@mui/icons-material'
import {Alert} from '@mui/material'
import Head from 'next/head'
interface User {
    email: string
    password: string
    message: string,
    phone: number, 
    name: string,
    repeat_password: string,
    address: string,
}

interface UserDetail {
    email: string
    password: string
    phone: string, 
    name: string,
    repeat_password: string,
    address: string,
}
export default function Signup() {
    const [user, setUser] = useState<User>({email: '', password: '', message: '', phone: undefined, name: '', repeat_password: '', address: ''})
    const [userDetail, setUserDetail] = useState<UserDetail>({email: 'gray-300', password: 'gray-300', phone: 'gray-300', name: 'gray-300', repeat_password: 'gray-300', address: 'gray-300'})
    const strongRegex = new RegExp("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=.{8,})");
    const mediumRegex = new RegExp("^(((?=.*[a-z])(?=.*[A-Z]))|((?=.*[a-z])(?=.*[0-9]))|((?=.*[A-Z])(?=.*[0-9])))(?=.{6,})");
    const [alert, setAlert] = useState(false)
    const [view, setView] = useState(false)
    const [checkedPassword, setCheckedPassword] = useState(false)
    const handleUser = async(e: { preventDefault: () => void; }) => {
        e.preventDefault()
        try {
            if(user.password != '' && checkedPassword && user.email && user.phone && user.name ) {
                const data = await axios.post('/api/user', null, {params: {email: user.email, password: user.password, name: user.name, phone: user.phone, login: 'teachers', address: user.address}})
                data.data.result ? setView(true) : setView(false)
                data.data ? setAlert(true) : setAlert(false)
                setUser((user) => ({...user, message: data.data.message}))
                setUser((user) => ({...user, name: '', phone: undefined, email: '', password:'', repeat_password:''}))
            } else {
                setUser((user) => ({...user, message: 'Error'}))
                // user.password ? setUserDetail((userDetail) => ({...userDetail, password: 'orange-800'})) : null
                // user.name ? setUserDetail((userDetail) => ({...userDetail, name: 'orange-800'})) : null
                if (!user.name) {
                    setAlert(true)
                    setUser((user) => ({...user, message: 'Нэрээ оруулна уу'}))
                } else if (!user.email) {
                    setAlert(true) 
                    setUser((user) => ({...user, message: 'И-майл ээ оруулна уу'}))
                } else if (!user.phone) {
                    setAlert(true) 
                    setUser((user) => ({...user, message: 'Утасны дугаараа оруулна уу'}))
                } else if (!user.password) {
                    setAlert(true) 
                    setUser((user) => ({...user, message: 'Нууц үгээ оруулна уу'}))
                } if (!checkedPassword) {
                    setAlert(true) 
                    setUser((user) => ({...user, message: 'Давтан нууц үгээ оруулна уу'}))
                } else{
                    setAlert(false)
                }

                user.phone ? setUserDetail((userDetail) => ({...userDetail, phone: 'orange-800'})) : null
                user.email ? setUserDetail((userDetail) => ({...userDetail, email: 'orange-800'})) : null
            }
        } catch (error) {
            console.log(error)
        }
    }

    const analyzePassword = async(e: {preventDefault: () => void;}) => {
        e.preventDefault()
        if(strongRegex.test(e.target.value)) {
            setUser((user) => ({...user, password: e.target.value}))
        } else if(mediumRegex.test(e.target.value)) {
            setUser((user) => ({...user, password: e.target.value}))
        }else {
            setUser((user) => ({...user, password: ''}))
        }
    }
    const checkPassword = async(e: {preventDefault: () => void;}) => {
        e.preventDefault()
        if (user.password == e.target.value) {
            setCheckedPassword(true) 
            setUser((user) => ({...user, repeat_password: e.target.value}))
            setAlert(false)
        } else {
            setUserDetail((userDetail) => ({...userDetail, repeat_password: 'orange-800'}))
            setAlert(true)
            setUser((user) => ({...user, message: 'Давтан нууц үг буруу байна.'}))
            setCheckedPassword(false)
        }
    }
    return (
        <>
        <Head>
        <title>Бүртгүүлэх</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./img/logo/lil_logo.png" />
      </Head>
        <div className="flex">
                <header className="flex-1 h-screen  px-6 py-8 main_bg">
                    <div className="h-20 w-20 relative">
                        <Image src="/img/logo/lil_logo.png" alt="logo" layout='fill' />
                    </div>
                    <div className="relative top-1/2 text-white navbar">
                        <h2 className="font-bold mb-4 text-xl">Lorem, ipsum.</h2>
                        <p className='mb-2'>
                            <CheckCircle sx={{marginRight: '0.8rem', fill: '#8dc75f'}}/>
                            <span>Lorem, ipsum dolor.</span>
                        </p>
                        <p className='mb-2'>
                            <CheckCircle sx={{marginRight: '0.8rem', fill: '#8dc75f'}}/>
                            <span>Lorem, ipsum dolor.</span>
                        </p>
                        <p className='mb-2'>
                            <CheckCircle sx={{marginRight: '0.8rem', fill: '#8dc75f'}}/>
                            <span>Lorem, ipsum dolor.</span>
                        </p>
                        <p className='mb-2'>
                            <CheckCircle sx={{marginRight: '0.8rem', fill: '#8dc75f'}}/>
                            <span>Lorem, ipsum dolor.</span>
                        </p>
                    </div>
                </header>
                <div className="sign">
                <nav className=" py-3 px-6">
                        <p className="text-right">Бүртгэлтэй юу? 
                            <Link href='/teacher'><a className="font-semibold cursor-pointer"> Нэвтрэх</a></Link>
                        </p>
                    </nav>
                    <form action="" onSubmit={handleUser} className='nav relative top-1/2 nav left-1/4 w-96'>
                    <h2 className="text-2xl font-bold mb-4">Бүртгүүлэх</h2>
                    {user.message && view && <Alert severity='success' className="mb-3">{user.message}</Alert>}
                    { alert && !view && <Alert severity='error' className="mb-3">{user.message}</Alert>}
                    <input type="text" onChange={(e) => setUser((user) => ({...user, name: e.target.value }))} className={`border rounded-md border-${userDetail.name} w-full px-3 py-2 mb-3`} placeholder="Name" value={user.name}/>

                    <input type="tel" onChange={(e) => setUser((user) => ({...user, phone: Number(e.target.value) }))} className={`border rounded-md border-${userDetail.phone} w-full px-3 py-2 mb-3`} placeholder="Phone" value={user.phone}/>

                    <input type="email" onChange={(e) => setUser((user) => ({...user, email: e.target.value }))} className={`border rounded-md border-${userDetail.email} w-full px-3 py-2 mb-3`} placeholder="Email" value={user.email}/>
                    <input type="text" onChange={(e) => setUser((user) => ({...user, address: e.target.value }))} className={`border rounded-md border-${userDetail.email} w-full px-3 py-2 mb-3`} placeholder="Address" value={user.address}/>

                    <input type="password" name="password" id="password" onChange={analyzePassword} className={`border rounded-md border-${userDetail.password} w-full px-3 py-2 mb-3`} placeholder="Password" />

                    <input type="password" name="repeat_password" id="repeat_password" onChange={checkPassword} className={`border-2 rounded-md border-${userDetail.repeat_password} w-full px-3 py-2 mb-3`} placeholder="Repeat password" />

                    <button type="submit" className='rounded-md main_bg w-full px-2 py-2 mb-3 text-white font-semibold' >Бүртгүүлэх</button>
                </form>
                </div>
        </div>
        </>
    )
}