import { useState, useEffect } from "react"
import axios from "axios"
import { useRouter } from "next/router";
import { NextRouter } from "next/router";
import * as React from "react";
import { styled, Theme, useTheme } from "@mui/material/styles";
import {Box, Toolbar, List, CssBaseline, Divider, IconButton, ListItem, ListItemIcon, ListItemText} from '@mui/material'
import MuiDrawer from "@mui/material/Drawer";
import MuiAppBar from "@mui/material/AppBar";
import Navbar from "../../src/components/student/Navbar";
import {
  Dashboard,
  LocalLibrary,
  Person,
  EventAvailable,
  Menu,
  ChevronLeft,
  School,
  HistoryEdu,
  AddTask
} from "@mui/icons-material";
import AdminTeacher from '../components/admin/teacher'
import AdminGroup from '../components/admin/group'
import AdminStudent from '../components/admin/student'
import AdminAddStudent from '../components/admin/student/group'
import Head from "next/head";
function SidebarIcon(props: any) {
  switch (props.index) {
    case 0:
      return <School />;
    case 1:
      return < HistoryEdu/>;
    case 2: 
       return <LocalLibrary />
    case 3:
      return <AddTask />
    default:
      return <></>;
  }
}
function AdminDashboards(props: { sidebar: string; }) {
  switch (parseInt(props.sidebar)) {
    case 0:
      return <AdminTeacher />;
    case 1:
      return < AdminGroup/>;
    case 2: 
      return < AdminStudent />;
    case 3:
      return < AdminAddStudent />
    default:
      return <></>;
  }
}
const drawerWidth = 240;

const openedMixin = (theme: Theme) => ({
  width: drawerWidth,
  transition: theme.transitions.create("width", {
    easing: theme.transitions.easing.sharp,
    duration: theme.transitions.duration.enteringScreen,
  }),
  overflowX: "hidden",
});

const closedMixin = (theme: Theme) => ({
  transition: theme.transitions.create("width", {
    easing: theme.transitions.easing.sharp,
    duration: theme.transitions.duration.leavingScreen,
  }),
  overflowX: "hidden",
  width: `calc(${theme.spacing(7)} + 1px)`,
  [theme.breakpoints.up("sm")]: {
    width: `calc(${theme.spacing(9)} + 1px)`,
  },
});

const DrawerHeader = styled("div")(({ theme }) => ({
  display: "flex",
  alignItems: "center",
  justifyContent: "flex-end",
  padding: theme.spacing(0, 1),
  // necessary for content to be below app bar
  ...theme.mixins.toolbar,
}));

const AppBar = styled(MuiAppBar, {
  shouldForwardProp: (prop) => prop !== "open",
})(({ theme, open }) => ({
  zIndex: theme.zIndex.drawer + 1,
  transition: theme.transitions.create(["width", "margin"], {
    easing: theme.transitions.easing.sharp,
    duration: theme.transitions.duration.leavingScreen,
  }),
  ...(open && {
    marginLeft: drawerWidth,
    width: `calc(100% - ${drawerWidth}px)`,
    transition: theme.transitions.create(["width", "margin"], {
      easing: theme.transitions.easing.sharp,
      duration: theme.transitions.duration.enteringScreen,
    }),
  }),
}));

const Drawer = styled(MuiDrawer, {
  shouldForwardProp: (prop) => prop !== "open",
})(({ theme, open }) => ({
  width: drawerWidth,
  flexShrink: 0,
  whiteSpace: "nowrap",
  boxSizing: "border-box",
  ...(open && {
    ...openedMixin(theme),
    "& .MuiDrawer-paper": openedMixin(theme),
  }),
  ...(!open && {
    ...closedMixin(theme),
    "& .MuiDrawer-paper": closedMixin(theme),
  }),
}));


  
export default function Admin() {
  const theme = useTheme();
  const [open, setOpen] = React.useState(false);
  const [sidebar, setSidebar] = useState(0);
  const handleDrawerOpen = () => {
    setOpen(true);
  };

  const handleDrawerClose = () => {
    setOpen(false);
  };

  const handleSidebar = (e: { target: { id: React.SetStateAction<number>; }; }) => {
    setSidebar(e.target.id);
  };
    const router:NextRouter = useRouter()
    const {slug} = router.query
    const [user, setUser] = useState([])
    const loadUser = async() => {
        try {
            const data = await axios.get(`/api/admin/${slug}`)
            data.data[0] === undefined || data.data.isLogin ? router.push('/admin/Login') : null
            setUser(data.data)
        } catch (error) {
            console.log(error)
        }
    }
    useEffect(() => {
         loadUser() 
    },[]);
    
    const handleLogout = async(e: { preventDefault: () => void; }) => {
        e.preventDefault()
        router.push('/')
        setUser([])
        try {
            await axios.patch(`/api/user/${slug}`, {params: {login: 'students'}})
        }catch(error) {
            console.log(error)
        }
    }
    return (
      <Box sx={{ display: "flex" }}>
      <Head>
        <title>Админ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo/lil_logo.png" />
      </Head>
      <CssBaseline />
      <AppBar
        position="fixed"
        open={open}
        className="bg-white shadow-none py-2"
      >
        <Toolbar>
          <IconButton
            className="text-black"
            aria-label="open drawer"
            onClick={handleDrawerOpen}
            edge="start"
            sx={{
              marginRight: "36px",
              ...(open && { display: "none" }),
            }}
          >
            <Menu/>
          </IconButton>
          <Navbar dashboard={sidebar} />
        </Toolbar>
      </AppBar>

      <Drawer variant="permanent" open={open}>
        <DrawerHeader>
          <div onClick={handleDrawerClose}>
            {theme.direction === "rtl" ? (
              <IconButton>
                <ChevronLeft />
              </IconButton>
            ) : (
              <div className="flex">
                <img src="/img/logo/logo_png.png" alt="logo" className="h-10" />
                <IconButton>
                  <ChevronLeft />
                </IconButton>
              </div>
            )}
          </div>
        </DrawerHeader>
        <Divider />
        <List>
          {["Багш нар", "Ангиуд", "Сурагчид", "Хичээл нээх"].map(
            (text, index) => (
              <ListItem
                button
                key={text}
                className="relative sidebar_current my-2 "
              >
                <ListItemIcon>
                  <SidebarIcon index={index} />
                </ListItemIcon>
                <ListItemText primary={text} />
                <span
                  className="absolute z-20 inset-0 "
                  onClick={handleSidebar}
                  id={index}

                ></span>
              </ListItem>
            )
          )}
        </List>
        {/* <Divider />
        <List>
          {["All mail", "Trash", "Spam"].map((text, index) => (
            <ListItem button key={text}>
              <ListItemIcon>
                {index % 2 === 0 ? <InboxIcon /> : <MailIcon />}
              </ListItemIcon>
              <ListItemText primary={text} />
            </ListItem>
          ))}
        </List> */}
      </Drawer>
      <Box component="main" sx={{ flexGrow: 1, p: 3, ml: 3 }}>
        <DrawerHeader />

        <AdminDashboards sidebar={sidebar} />
      </Box>
    </Box>
    )
}